name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  push-image-id:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: zakariahoussa/gitops-app-config
          
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
        
      - name: Generate API module
        run: |
                  git config user.name "zakariahoussa"
                  git config user.email "dev@example.com"

      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        with:
          repository_owner: zakariahoussa
          repository_name: gitops-app-config
          new_branch_name: titi
          access_token: ${{ secrets.ACCESS_TOKEN}}
                  
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'application.yaml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
          commitChange: true
          updateFile: true
          branch: titi
          targetBranch: main
          createPR: true
          repository: zakariahoussa/gitops-app-config
          message: 'Update Image Version' 
  build-and-push-image:
    needs: push-image-id
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          

